### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by jhpalmieri** [cnassau/steenrod#1]
I can't build this on a few different Macs (one Intel, one Apple Silicon). I get messages like this:
```
../src/steenrod.cc:172:14: error: cannot initialize a variable of type 'Tcl_Obj *' with an rvalue of type 'void *'
    Tcl_Obj *dg = NULL, *theGObj;
             ^    ~~~~

../src/steenrod.cc:183:12: error: assigning to 'matrixType *' from incompatible type 'void *'
    *mtp = NULL; *mat = NULL; /* if non-zero, caller will free this */
           ^~~~

../src/steenrod.cc:241:5: error: cannot initialize a parameter of type 'const char *' with an rvalue of type 'void *'
    PROGVARINIT;
    ^~~~~~~~~~~
```
This happens with the built-in `gcc` and `g++` (which I think come from clang), but also if I use `export CC=gcc-13` and `export CXX=g++-13` to use the homebrew installation of `gcc`.

**Comment by cnassau** [comment]
Hi John,
I tried to reproduce this on Linux using a build in an alpine container which comes with gcc-13.2, but I don't get this problem.  I did switch from C to C++ recently, and this is notoriously stricter about types than C, so maybe that is the source of the problem.

Currently, I'm #defining NULL on top of steenrod.cc in case it is not provided by the build environment:
```c++
#ifndef NULL
#  define NULL ((void*)0)
#endif
``` 
Does it help if you leave out the "(void*)" here?

**Comment by jhpalmieri** [comment]
Yes, if I use `#  define NULL (0)`, then `make` finishes without error.

**Comment by cnassau** [comment]
Great, I've pushed that change right now.  Thanks for testing!
